#!/bin/bash
base_path=`pwd`

#開發測試中Beta
if [ "${1}" == "alias" ]; then
calias="alias console=${base_path}/console"
echo ${calias}
exit;
fi

#下載images
if [ "${1}" == "pull" ]; then
    docker pull nginx 
    docker pull mysql:5.6.31
    docker pull deviny/fpm:7.0.11
    exit;
fi

#變更模式, web:80, db:127.0.0.1:3306
if [ "${1}" == "mode1" ]; then
    docker-compose down
    echo "docker-compose setting file changed."
    echo "HOST DB: listen on 127.0.0.1:3306."
    echo "HOST WEB: listen on port 80."
    ln -vsf docker-compose-mode1.yml docker-compose.yml
    docker-compose up -d
    ./console info
    exit;
fi

#隨機
if [ "${1}" == "random" ]; then
    docker-compose down
    echo "docker-compose setting file changed."
    echo "HOST DB: listen on random port."
    echo "HOST WEB: listen on random port."
    ln -vsf docker-compose-random.yml docker-compose.yml
    docker-compose up -d
    ./console info
    exit;
fi

#Custom Config
if [ "${1}" == "custom" ]; then
    if [ -e docker-compose-custom.yml ]; then
        docker-compose down
        ln -vsf docker-compose-custom.yml docker-compose.yml 
        docker-compose up -d
    else
        cp docker-compose-random.yml docker-compose-custom.yml
        ln -vsf docker-compose-custom.yml docker-compose.yml 
        echo "docker-compose-custom.yml is created."
        docker-compose up -d
    fi 
    ./console info
    exit;
fi


#停止docker-compose
if [ "${1}" == "down" ]; then
docker-compose down
exit;
fi

#重啟
if [ "${1}" == "restart" ]; then
docker-compose down
docker-compose up -d
echo "DB:"
./scripts/db-ports
echo "Web:"
./scripts/web-ports
exit;
fi

if [ "${1}" == "up" ]; then
docker-compose up -d
echo "DB:"
#設定DB的時區到Asia/Taipei
./scripts/db-ports
echo "Web:"
./scripts/web-ports
exit;
fi

#進資料庫
if [ "${1}" == "mysql" ]; then
docker-compose exec db mysql
exit;
fi

#啟動時檢測網頁資訊
if [ "${1}" == "info" ]; then
echo "DB:"
./scripts/db-ports
echo "Web:"
./scripts/web-ports
exit;
fi

#執行ps
if [ "${1}" == "ps" ]; then
echo ${base_path}
docker-compose -f ${base_path}/docker-compose.yml ps
exit
fi

#重新載入nginx設定
if [ "${1}" == "reload" ]; then
docker-compose exec web nginx -s reload
exit
fi

#檢測是否執行
docker-compose -f ${base_path}/docker-compose.yml ps |grep -q 9000
if [ $? -eq 1 ]; then
docker-compose up -d
fi
docker-compose -f ${base_path}/docker-compose.yml  exec php bash
