version: '3'
services:
### 網頁伺服器的container ##################################
 web:
  image: nginx
  dns: 8.8.8.8
  ports:
      #使用隨機的port 80
      - "80"
      - "443"
      #隨機的mysql連結埠
      - "3306"
  volumes:
  - ./sites:/var/www/html
  - ./etc:/etc/nginx/conf.d
  hostname: d-laravel
  
### PHP-FPM container ##################################
 php:
  image: deviny/fpm:7.1.7
  #image: deviny/fpm:7.0.21
  #image: deviny/fpm:5.6.31
  network_mode: "service:web"

  volumes:
  - ./etc/php:/usr/local/etc/php
  - ./sites:/var/www/html
  #- ./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
  #- ./logs/php:/var/log
  #environment:
  #- PHP_IDE_CONFIG=serverName=dlaravel
  #- XDEBUG_CONFIG="remote_host=???? profiler_enable=1"
  #建立bash_aliases在etc下，可用來自訂dlaravel使用者的環境變數
  #- ./etc/bash_aliases:/home/dlaravel/.bash_aliases

### 資料庫 container ##################################
 db:
  image: mysql:5.7.17
  network_mode: "service:web"

  environment:
   - MYSQL_DATABASE=homestead
   - MYSQL_USER=homestead
   - MYSQL_PASSWORD=secret
   - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
   - TZ=Asia/Taipei

  volumes:
      - ./data:/var/lib/mysql
      #這裡的log依my.cnf的路徑設定，預設container在/var/log/mysql
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./logs/db:/var/log/mysql
