version: '3.6'
services:
 web:
  image: nginx
  dns: 8.8.8.8
  ports:
    - "80:80"
    - "443:443"
  volumes:
  - ./sites:/var/www/html
  - ./etc:/etc/nginx/conf.d
  hostname: web
  networks:
    - dlaravel_net
  
 php:
  image: mydlaravelfpm
  build:
     context: ./dockerfiles/fpm/
     dockerfile: Dockerfile_php_7.4.x
  network_mode: "service:web"
  volumes:
  - ./etc/php:/usr/local/etc/php/conf.d
  - ./sites:/var/www/html
  - ./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
  - ~/.dlaravel/cache:/home/dlaravel/.composer/cache
  environment:
   - TZ=Asia/Taipei
 db:
  image: mysql:8.0.18
  command: --default-authentication-plugin=mysql_native_password
  hostname: db
  ports:
    - "3306"
  volumes:
    - ./data:/var/lib/mysql
  environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
   - TZ=Asia/Taipei
  networks:
    - dlaravel_net

networks:
    dlaravel_net:
