version: '2'
services:
 web:
  image: nginx
  dns: 8.8.8.8
  ports:
      #使用port 80
      - "80:80"
      #系統隨機，防址開多個時會衝突
      #- "80"
  volumes:
  - ./sites:/var/www/html
  - ./etc:/etc/nginx/conf.d

  hostname: web

 php:
  image: deviny/fpm:7.0.10

  volumes:
   - ./sites:/var/www/html
   - ./etc/php:/usr/local/etc/php

  hostname: php

 db:
  image: mysql:5.6.31

  environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Taipei

  volumes:
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
  ports:
      #- "3306:3306"
      #只綁定localhost
      - "127.0.0.1:3306:3306"
      # 隨機的mysql連結埠
      #- "3306"
  hostname: db
