version: '2'
services:
### 網頁伺服器的container ##################################
 web:
  image: nginx
  dns: 8.8.8.8
  ports:
      # 使用隨機的port 80
      - "80"
      - "443"
      # 隨機的mysql連結埠
      - "3306"
  volumes:
  - ./sites:/var/www/html
  - ./etc:/etc/nginx/conf.d
  hostname: d-laravel
  
### PHP-FPM container ##################################
 php:
  image: deviny/fpm:7.1.2
  network_mode: "service:web"

  volumes:
  - ./etc/php:/usr/local/etc/php
  - ./sites:/var/www/html
  #environment:
  #- PHP_IDE_CONFIG=serverName=dlaravel
  #- XDEBUG_CONFIG="remote_host=???? profiler_enable=1"
  #建立bash_aliases在etc下，可用來自訂dlaravel使用者的環境變數
  #- ./etc/bash_aliases:/home/dlaravel/.bash_aliases

### 資料庫 container ##################################
 db:
  image: mysql:5.7.17
  network_mode: "service:web"

  environment:
   - MYSQL_DATABASE= homestead
   - MYSQL_USER= homestead
   - MYSQL_PASSWORD= secret
   #變更mysql_root預設密碼，請同時調整dlaravle下的etc/mysql/my.cnf
   - MYSQL_ROOT_PASSWORD=secret
   #- MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
   - TZ= Asia/Taipei

  volumes:
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
