version: '2'
services:
 web:
  image: nginx
  dns: 8.8.8.8
  ports:
      #使用固定 port 80
      - "80:80"
      #只綁定localhost
      - "127.0.0.1:3306:3306"
  volumes:
  - ./sites:/var/www/html
  - ./etc:/etc/nginx/conf.d
  hostname: d-laravel
  
 php:
  image: deviny/fpm:7.1
  network_mode: "service:web"

  volumes:
  - ./etc/php:/usr/local/etc/php
  - ./sites:/var/www/html

 db:
  image: mysql:5.6.31
  network_mode: "service:web"

  environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Taipei

  volumes:
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
