version: '3.6'
services:
#=== web service ======================
 web:
  image: httpd:2.4
  ports:
   - "80:80"
  volumes:
   - ./sites:/usr/local/apache2/htdocs
   # test1.test & test2.test (You have to modify vhost for your own)
   - ./etc/httpd/httpd.conf.sample:/usr/local/apache2/conf/httpd.conf
  networks:
   - dlaravel_net
  
#=== php service ==========================
 php:
  network_mode: "service:web"
  image: deviny/fpm:8.0.8
  volumes:
    - ./etc/php:/usr/local/etc/php/conf.d
    - ./sites:/var/www/html
    - ./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ~/.dlaravel/cache:/home/dlaravel/.composer/cache
  environment:
    - TZ=Asia/Taipei

#=== db service ===========================
 db:
  image: mariadb:10.5.5
  #command: --default-authentication-plugin=mysql_native_password --sql_mode=""
  hostname: db
  ports:
    - "127.0.0.1:3306:3306"
  volumes:
    - ./data:/var/lib/mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
    - TZ=Asia/Taipei
  networks:
    - dlaravel_net

#=== top-level netowks key ======================
networks:
    dlaravel_net:
