version: '3.6'
services:
#=== web service ======================
 web:
  image: httpd:2.4
  ports:
   - "80:80"
  volumes:
   - ./sites:/usr/local/apache2/htdocs
   # test1.test & test2.test (You have to modify vhost for your own)
   - ./etc/httpd/httpd.conf.sample:/usr/local/apache2/conf/httpd.conf
  networks:
   - dlaravel_net
  
#=== php service ==========================
 php:
  network_mode: "service:web"
  image: deviny/fpm:7.4.3ssh
  volumes:
  - ./etc/php:/usr/local/etc/php/conf.d
  - ./sites:/var/www/html:cached
  - ./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
  - ~/.ssh:/home/dlaravel/.ssh
  ###create composer cache###
  - ~/.dlaravel/cache:/home/dlaravel/.composer/cache
  #- ./var/log/php:/var/log
  #- ./etc/supervisor:/etc/supervisor/conf.d
  #- ./var/log/supervisor:/var/log/supervisor
  environment:
   - TZ=Asia/Taipei
  #- PHP_IDE_CONFIG=serverName=dlaravel
  #- XDEBUG_CONFIG="remote_host=???? profiler_enable=1"
  #- ./etc/bash_aliases:/home/dlaravel/.bash_aliases
  #command: bash -c "php-fpm -D&&php /var/www/html/default/bin/laravels start"
  #networks:
  #  - dlaravel_net

#=== db service ===========================
 db:
  image: mysql:8.0.18
  command: --default-authentication-plugin=mysql_native_password
  hostname: db
  ports:
    - "127.0.0.1:3306:3306"
  volumes:
    - ./data:/var/lib/mysql
  environment:
   #- MYSQL_DATABASE=homestead
   #- MYSQL_USER=homestead
   #- MYSQL_PASSWORD=secret
   #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-secret}
   - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
   - TZ=Asia/Taipei
  networks:
    - dlaravel_net

#=== top-level netowks key ======================
networks:
    dlaravel_net:
