version: '3.6'
services:
#=== web service ======================
 web:
  image: nginx
  dns: 8.8.8.8
  ports:
    - "80:80"
    - "443:443"
    - "127.0.0.1:2020:22"
    #for echo-server
    #- "6001:6001"
  volumes:
    - ./sites:/var/www/html
    - ./etc:/etc/nginx/conf.d
  hostname: web
  networks:
    - dlaravel_net
  
#=== php service ==========================
 php:
  network_mode: "service:web"
  image: deviny/fpm:8.0.7ssh
  volumes:
    - ./etc/php:/usr/local/etc/php/conf.d
    - ./sites:/var/www/html:cached
    - ./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ~/.ssh/id_rsa.pub:/home/dlaravel/.ssh/authorized_keys
    - ~/.dlaravel/cache:/home/dlaravel/.composer/cache
  environment:
    - TZ=Asia/Taipei

#=== db service ===========================
 db:
  image: mariadb:10.5.5
  #command: --default-authentication-plugin=mysql_native_password --sql_mode=""
  hostname: db
  ports:
    - "127.0.0.1:3306:3306"
  volumes:
    - ./data:/var/lib/mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
    - TZ=Asia/Taipei
  networks:
    - dlaravel_net

#=== top-level netowks key ======================
networks:
    dlaravel_net:
