version: '3.6'
services:
#=== web container ======================
 web:
  image: nginx
  dns: 8.8.8.8
  ports:
    # random port
    - "80"
    - "443"
  volumes:
  - ./sites:/var/www/html:cached
  - ./etc:/etc/nginx/conf.d
  hostname: web
  networks:
    - dlaravel_net
  
#=== php service ==========================
 php:
  network_mode: "service:web"
  image: deviny/fpm:7.4.8
  volumes:
    - ./etc/php:/usr/local/etc/php/conf.d
    - ./sites:/var/www/html:cached
    - ./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ~/.dlaravel/cache:/home/dlaravel/.composer/cache
  environment:
    - TZ=Asia/Taipei

#=== db service ===========================
 db:
  image: mysql:8.0.19
  command: --default-authentication-plugin=mysql_native_password --sql_mode=""
  hostname: db
  ports:
    - "3306"
  volumes:
    - ./data:/var/lib/mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
    - TZ=Asia/Taipei
  networks:
    - dlaravel_net

#=== top-level netowks key ======================
networks:
    dlaravel_net:
