#docker stack deploy -c stack.yaml dlaravel
version: '3.6'
services:
#=== web service ======================
 web:
  image: dlaravel_web
  dns: 8.8.8.8
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - sites:/var/www/html
  hostname: web
  networks:
    - dlaravel_net
  
#=== php service ==========================
 php:
  network_mode: "service:web"
  image:  dlaravel_php
  volumes:
    - sites:/var/www/html
    - php_session:/var/lib/php/session
  environment:
    - TZ=Asia/Taipei

#=== db service ===========================
 db:
  image: db
  hostname: dlaravel_db
  ports:
    - "3306"
  volumes:
    - data:/var/lib/mysql
  environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
   - TZ=Asia/Taipei
  networks:
    - dlaravel_net

#===============================================
volumes:
  cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/etc/cache/cache
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data
  sites:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/sites
  php_session:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/php_session

#=== top-level netowks key ======================
networks:
    dlaravel_net:
