version: '3.6'
services:
  php81:
    image: deviny/fpm:8.1.14
    build:
      context: .
      dockerfile: Dockerfile_php_8.1.x

  php80:
    image: deviny/fpm:8.0.23
    build:
      context: .
      dockerfile: Dockerfile_php_8.0.x

  phpssh:
    image: deviny/fpm:8.1.14-ssh
    build:
      context: .
      dockerfile: Dockerfile_php_ssh

  phpssh74:
    image: deviny/fpm:7.4.30-ssh
    build:
      context: .
      dockerfile: Dockerfile_php_ssh_7.4

  php74:
    image: deviny/fpm:7.4.30
    build:
      context: .
      dockerfile: Dockerfile_php_7.4.x
