version: '3.6'
services:
  php80:
    image: deviny/fpm:8.0.8
    build:
      context: .
      dockerfile: Dockerfile_php_8.0.x

  phpssh:
    image: deviny/fpm:8.0.8ssh
    build:
      context: .
      dockerfile: Dockerfile_php_ssh

  latest:
    image: deviny/fpm:latest
    build:
      context: .
      dockerfile: Dockerfile_php_8.0.x

  php74:
    image: deviny/fpm:7.4.21
    build:
      context: .
      dockerfile: Dockerfile_php_7.4.x


  php73:
    image: deviny/fpm:7.3.29
    build:
      context: .
      dockerfile: Dockerfile_php_7.3.x

  php72:
    image: deviny/fpm:7.2.34
    build:
      context: .
      dockerfile: Dockerfile_php_7.2.x
