version: '3.6'
services:
  php81:
    image: deviny/fpm:8.1.0
    build:
      context: .
      dockerfile: Dockerfile_php_8.1.x

  php80:
    image: deviny/fpm:8.0.13
    build:
      context: .
      dockerfile: Dockerfile_php_8.0.x

  phpssh:
    image: deviny/fpm:8.1.0-ssh
    build:
      context: .
      dockerfile: Dockerfile_php_ssh

  latest:
    image: deviny/fpm:latest
    build:
      context: .
      dockerfile: Dockerfile_php_8.1.x

  php74:
    image: deviny/fpm:7.4.26
    build:
      context: .
      dockerfile: Dockerfile_php_7.4.x

  php73:
    image: deviny/fpm:7.3.33
    build:
      context: .
      dockerfile: Dockerfile_php_7.3.x

  php72:
    image: deviny/fpm:7.2.34
    build:
      context: .
      dockerfile: Dockerfile_php_7.2.x
