#用來提升網頁io的速度
### beanstalk container ##################################
version: '3'
services:
 bg-sync:
    image: cweagans/bg-sync
    volumes:
      - ./../sites:/source
    volumes_from:
      - web
    environment:
      - SYNC_DESTINATION=/var/www/html
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true
