#Dockerhub官方jenkins LTS image
version: '3.6'
services:
 ci:
  image: jenkins/jenkins:lts
  dns: 8.8.8.8
  ports:
      - "8080:8080"
      - "50000:50000"
  volumes:
   - ./var/jenkins_home:/var/jenkins_home
   - ./var/jenkins_home/workspace:/var/jenkins_home/workspace
  networks:
    - dlaravel_net

networks:
    dlaravel_net:
