version: '2'
services:
 web:
  image: nginx
  dns: 8.8.8.8
  ports:
      # 使用隨機的port 80
      - "80:80"
      - "443:443"
      # 隨機的mysql連結埠
      - "127.0.0.1:3306:3306"
      # Beanstalk
      - "11300:11300"
  volumes:
  - ./sites:/var/www/html
  - ./etc:/etc/nginx/conf.d
  hostname: d-laravel
  
 php:
  image: deviny/fpm:7.1.1
  #image: deviny/fpm:5.6.30
  #image: deviny/fpm:5.6.30
  network_mode: "service:web"

  volumes:
  - ./etc/php:/usr/local/etc/php
  - ./sites:/var/www/html

 db:
  image: mysql:5.7.17
  network_mode: "service:web"

  environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Taipei

  volumes:
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
 #非官方的版本，不過星星數最高的，我測過有作用
 beanstalk:
   image: bevand10/alpine-beanstalk
   network_mode: "service:web"
