#!/bin/bash
uid=`whoami|id -u`
if [ ${uid} -eq 0 ]; then
    echo "Don't run D-Laravel as root!"
    exit;
fi

scripts_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dlaravel_path=${PWD##*/}

if [[ ${dlaravel_path} =~ [_] ]]; then
    echo "D-Laravel folder can't have underscore. [${dlaravel_path}]";
    exit;
fi

base_path=`echo ${scripts_path}|sed 's#/scripts##'`
containerName=`printf '%s\n' "${base_path##*/}"|tr '[:upper:]' '[:lower:]'|sed 's/-//g'|sed 's/\.//g'`
hosts_file='/etc/hosts'
#檢測是否有docker-compose連結，沒有就建一個
if [ ! -f "${base_path}/docker-compose.yml" ];then
    ln -vsf docker-compose-random.yml docker-compose.yml
fi
#檢測是否為widnows desktop

which docker >/dev/null 2>&1
if [ $? -eq 1 ]; then
echo 'Please go to https://docs.docker.com/engine/installation/ to install docker'
exit;
fi

which docker-compose >/dev/null 2>&1
if [ $? -eq 1 ]; then
echo 'Please go to https://docs.docker.com/compose/install/ to install docker-compose'
exit
fi


winpty=""
#is windows
which winpty >/dev/null 2>&1
if [ $? -eq 0 ]; then
    winpty=`which winpty`
    hosts_file='/c/Windows/system32/drivers/etc/hosts'
fi
    

