#!/bin/bash
base_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${base_path}/checker

docker ps |grep -q ${containerName}_web_1
if [ $? -eq 1 ]; then
echo ${containerName}_db_1 is not running
exit
fi

#docker inspect --format='{{range $p, $conf := .NetworkSettings.Ports}} {{$p}} -> {{(index $conf 0).HostPort}} {{end}}' ${containerName}_web_1
db_port=`docker inspect --format='{{(index (index .NetworkSettings.Ports "3306/tcp") 0).HostPort}}'  ${containerName}_web_1`
echo "host:${db_port}"


