#!/bin/bash
#set -e
#get the scripts path
scripts_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
base_path=`echo ${scripts_path}|sed 's#/scripts##'`

#check docker-compose file is readable
function chk_docker_compose_file_is_readable {
    if [ ! -r "${base_path}/docker-compose.yml" ]; then
        echo "Soft link Error"
        echo "File ${base_path}/docker-compose.yml is not readdable!"
        echo "force link to ${base_path}/docker-compose-normal.yml"
        ln -vsf ${base_path}/docker-compose-normal.yml ${base_path}/docker-compose.yml
    fi
}
#array_service
function array_service {
        array_service=(${DOCKER_SERVICES})
        CONSOLE_CMD="-f ${base_path}/docker-compose.yml "
        for i in "${array_service[@]}"
        do
         : 
        CONSOLE_CMD+="-f ${base_path}/service/${i}.yml "
        done
}
#dlaravel console log
function console_logs {
    chk_docker_compose_file_is_readable 
    if [ -z "${DOCKER_SERVICES}" ]; then
     echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml ${@}"

            chk_project_mode

            if [ ${?} -eq 0 ]; then
                ${winpty} docker-compose -p ${project_name} -f ${base_path}/docker-compose.yml ${@}
            else
                ${winpty} docker-compose -f ${base_path}/docker-compose.yml ${@}
            fi

    else
     array_service
     echo "${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} ${@}"
     ${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} ${@}
    fi
}
#display logs when error
function fail_exit {
    if [ $? -eq 1 ]; then
        console_logs logs ${@}
        exit;
    fi
}

#spcify service restart
function console_restart {
    chk_docker_compose_file_is_readable 
    if [ -z "${DOCKER_SERVICES}" ]; then
     ${winpty} docker-compose -f ${base_path}/docker-compose.yml ${@}
    else
     array_service
     ${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} ${@}
    fi
}

#specify service up
function console_up_service {
    chk_docker_compose_file_is_readable 
    if [ -z "${DOCKER_SERVICES}" ]; then
     echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml up -d ${@}"
     ${winpty} docker-compose -f ${base_path}/docker-compose.yml up -d ${@}
    else
     array_service
     echo "${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} up -d ${@}"
     ${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} up -d ${@}
    fi
}

#display soft link
function console_link {
    link=$(ls -l ${base_path}/docker-compose.yml)
    target_link=$(echo ${link}|cut -d" " -f 11)
    if [ ! -z ${target_link} ]; then
      echo "Currently docker-compose.yml is soft link to ${target_link}"
    fi
}

#dlaravel console exec
function console_exec {
    chk_docker_compose_file_is_readable 
    if [ -z "${DOCKER_SERVICES}" ]; then
     echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml ${@}"
     ${winpty} docker-compose -f ${base_path}/docker-compose.yml ${@}
    else
     array_service
     echo "${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} ${@}"
     ${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} ${@}
    fi
}
function check_swoole {
    cat ${base_path}/etc/default.conf|grep -q laravels
    #發現laravels
    if [ ${?} -eq 0 ]; then
        echo -e "\nSwoole is enabled."
        echo "Default folder exist. (sites/default)"
        echo "http://localhost or http://your_ip_address"
        exit;
    fi
}
function chk_default_conf_exist {
    #檢測預設的設定檔是否存在
    if [ ! -f "${base_path}/etc/default.conf" ]; then
        cp ${base_path}/etc/default.sample ${base_path}/etc/default.conf
    fi
}

#is_project_mode
function chk_project_mode {
    project_name=$(dirname ${base_path}|/usr/bin/awk -F/ '{print $NF}')
    grep  -q dlaravel_project_mode ${base_path}/sites/${project_name}  >/dev/null 2>&1
    #ls -R ${base_path}/sites/${project_name} 1> /dev/null 2>/dev/null
}

#dlarave console up
function console_up {
    chk_default_conf_exist
    if [ ! -f "${base_path}/docker-compose.yml" ]; then
        echo ${base_path}
        #create soft link if no exists.
        ln -s ${base_path}/docker-compose-random.yml ${base_path}/docker-compose.yml
    fi
    console_link
    if [ -z "${DOCKER_SERVICES}" ]; then
        echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml up -d --remove-orphans"

            chk_project_mode
            if [ ${?} -eq 0 ]; then
                ${winpty} docker-compose -p ${project_name} -f ${base_path}/docker-compose.yml up -d --remove-orphans
            else
                ${winpty} docker-compose -f ${base_path}/docker-compose.yml up -d --remove-orphans
            fi
        else
        array_service
        echo "${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} up -d --remove-orphans"
        ${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} up -d --remove-orphans
    fi
        #暫時保留
        #${winpty} docker-compose exec web /bin/bash -c 'cd /etc/;ln -sf /usr/share/zoneinfo/Asia/Taipei localtime;dpkg-reconfigure -f noninteractive tzdata'
        check_swoole
        fail_exit ${base_path} 
    echo "DB:"
        #設定DB的時區到Asia/Taipei
        ${base_path}/scripts/db-ports
        echo "Web:"
        ${base_path}/scripts/web-ports
}
#dlarave console pull
function console_pull {
    if [ ! -f "${base_path}/docker-compose.yml" ]; then
        echo ${base_path}
        #檔案不存在，進行預設的soft link
        ln -s ${base_path}/docker-compose-random.yml ${base_path}/docker-compose.yml
    fi
    console_link
    if [ -z "${DOCKER_SERVICES}" ]; then
        echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml pull"
        ${winpty} docker-compose -f ${base_path}/docker-compose.yml pull
        else
        array_service
        echo "${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} pull"
        ${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} pull
    fi
}

#dlaravel console down
function console_down {
    chk_docker_compose_file_is_readable 
    if [ -z "${DOCKER_SERVICES}" ]; then
        if [ -e ${base_path}/docker-compose.yml ]; then
             echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml down --remove-orphans"

                chk_project_mode

                if [ ${?} -eq 0 ]; then
                 ${winpty} docker-compose -p ${project_name} -f ${base_path}/docker-compose.yml down --remove-orphans  
                else
                 ${winpty} docker-compose -f ${base_path}/docker-compose.yml down --remove-orphans  
                fi

            else
             echo "${winpty} docker-compose -f ${base_path}/docker-compose-random.yml down --remove-orphans"
             ${winpty} docker-compose -f ${base_path}/docker-compose-random.yml down --remove-orphans  
        fi
        else
        array_service
        echo "docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} down --remove-orphans"
        docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} down --remove-orphans 
    fi
}
#dlaravel console down
function console_down_silent {
    chk_docker_compose_file_is_readable 
    if [ -z "${DOCKER_SERVICES}" ]; then
        if [ -e ${base_path}/docker-compose.yml ]; then

                echo "docker-compose -f ${base_path}/docker-compose.yml down --remove-orphans"
                chk_project_mode       
                if [ ${?} -eq 0 ]; then
                    docker-compose -p ${project_name} -f ${base_path}/docker-compose.yml down --remove-orphans  > /dev/null 2>&1
                    rm ${base_path}/sites/${project_name}
                else
                    docker-compose -f ${base_path}/docker-compose.yml down --remove-orphans  > /dev/null 2>&1
                fi

            else
                echo "docker-compose -f ${base_path}/docker-compose-random.yml down --remove-orphans"
                docker-compose -f ${base_path}/docker-compose-random.yml down --remove-orphans  > /dev/null 2>&1
        fi
        else
        array_service
        echo "docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} down --remove-orphans" 
        docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} down --remove-orphans > /dev/null 2>&1
    fi
}
#dlaravel console ps
function console_ps {
    chk_project_mode
    if [ ${?} -eq 0 ]; then
        echo "Dlaravel is running in per project mode."
    fi
    chk_docker_compose_file_is_readable 
    if [ -f "${base_path}/.docker-compose.yml" ]; then
        echo "Can't find ${base_path}/docker-compose.yml"
    fi

    if [ -z "${DOCKER_SERVICES}" ]; then
          echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml ps"

                chk_project_mode

                if [ ${?} -eq 0 ]; then
                    ${winpty} docker-compose -p ${project_name} -f ${base_path}/docker-compose.yml ps
                else
                    ${winpty} docker-compose -f ${base_path}/docker-compose.yml ps
                fi
        else
        array_service
          echo "${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} ps"
          ${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} ps
    fi

}
#dlaravel console_top 
function console_top {
    chk_docker_compose_file_is_readable 
    if [ -f "${base_path}/.docker-compose.yml" ]; then
        echo "Can't find ${base_path}/docker-compose.yml"
    fi

    if [ -z "${DOCKER_SERVICES}" ]; then
          echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml top"
          ${winpty} docker-compose -f ${base_path}/docker-compose.yml top
        else
        array_service
          echo "${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} top"
          ${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} top
    fi

}

#specify service top
function console_top_service {
    chk_docker_compose_file_is_readable 
    if [ -z "${DOCKER_SERVICES}" ]; then
        echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml top ${@}"
        ${winpty} docker-compose -f ${base_path}/docker-compose.yml top ${@}
    else
     array_service
        echo "${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} top ${@}"
        ${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} top ${@}
    fi
}

#dlaravel console kill
function console_kill {
    if [ -z "${DOCKER_SERVICES}" ]; then
            echo "${winpty} docker-compose -f ${base_path}/docker-compose.yml down"
            ${winpty} docker-compose -f ${base_path}/docker-compose.yml down > /dev/null 2>&1
        else
        array_service
            echo "${winpty} docker-compose kill $(${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} ps -q)"
             ${winpty} docker-compose kill $(${winpty} docker-compose -p $(basename ${base_path}) ${CONSOLE_CMD} ps -q) > /dev/null 2>&1
    fi

}
