#!/bin/bash
#currentPath=`pwd`
base_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${base_path}/checker

echo "Reload web service: ${containerName}_web_1"
${winpty} docker exec -ti ${containerName}_web_1 nginx -s reload

