#!/bin/bash
scripts_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
base_path=`echo ${scripts_path}|sed 's#/scripts##'`
source ${base_path}/scripts/checker
source ${base_path}/scripts/functions

chk_project_mode

if [ ${?} -eq 0 ]; then
    docker-compose -p ${project_name} -f ${scripts_path}/../docker-compose.yml ps |grep ${project_name}_web_1|grep -q 'Up\|running'
    if [ ${?} -eq 1 ]; then
        echo "No service of web."
        exit;
    fi
    web="${project_name}_web_1"
else
    docker-compose -f ${scripts_path}/../docker-compose.yml ps |grep ${containerName}_web_1|grep -q 'Up\|running'
    if [ ${?} -eq 1 ]; then
        echo "No service of web."
        exit;
    fi
fi

if [ $? -eq 1 ]; then
echo ${containerName}_web_1 is not running
exit
fi

web_port=`${win_pty} docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}'  ${web}`
#查看sites內的資料夾數量
projectNum=`ls ${base_path}/sites/|wc -l`

#印出sites資料夾目錄，轉換為Web
if [ ${projectNum} -gt 0 ]; then
    #for Mac

is_enable_default=0
    if [ ${hosts_file} == '/etc/hosts' ]; then
for i in $(ls -d ${base_path}/sites/*|rev|cut -d/ -f1|rev); do 
        if [ ${i} == 'xdebug.log' ]; then
            continue
        fi
        if [ ${web_port} == 80 ]; then
            if [ ${i} != "default" ]; then
                if [ -f ${base_path}/etc/default-ssl.conf ]; then
                    echo -n https://;echo ${i}.test|cut -d/ -f 2; 
                else
                    echo -n http://;echo ${i}.test|cut -d/ -f 2; 
                fi
            else
                is_enable_default=1
            fi
        else
            if [ ${i} != "default" ]; then
                if [ -f ${base_path}/etc/default-ssl.conf ]; then
                    webs_port=`${win_pty} docker inspect --format='{{(index (index .NetworkSettings.Ports "443/tcp") 0).HostPort}}'  ${web}`
                    echo -n https://;echo ${i}.test:${webs_port}|cut -d/ -f 2; 
                else
                    echo -n http://;echo ${i}.test:${web_port}|cut -d/ -f 2; 
                fi
            else
                is_enable_default=1
            fi
        fi
done
    if [ ${is_enable_default} -eq 1 ]; then
        if [ ${web_port} -eq "80" ]; then
            echo -e "\nDefault folder exist.\nhttp://localhost or http://your_ip_address"
        else
            echo -e "\nDefault folder exist.\nhttp://localhost:${web_port} or http://your_ip_address:${web_port}"
        fi
    fi
    else
        echo "*.test, port:" ${web_port}
        ls -l sites/|cut -d ' ' -f 9
   fi 
fi

if [ ${projectNum} -eq 0 ]; then
    echo "No Projects are found, you can create one by following command."
    echo "For example as below:"
    echo "./create [project name]"
fi
#echo " http://0.0.0.0:${web_port}"

