#!/bin/bash
base_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
projectFolder=`echo ${base_path}|sed 's#/scripts##'`
source ${projectFolder}/scripts/checker

docker-compose -f ${base_path}/../docker-compose.yml ps |grep ${containerName}_web_1|grep -q Up
if [ $? -eq 1 ]; then
echo ${containerName}_web_1 is not running
exit
fi

web_port=`${win_pty} docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}'  ${containerName}_web_1`
#查看sites內的資料夾數量
projectNum=`ls ${projectFolder}/sites/|wc -l`

#印出sites資料夾目錄，轉換為Web
if [ ${projectNum} -gt 0 ]; then
    #for Mac
    if [ ${hosts_file} == '/etc/hosts' ]; then
for i in $(ls -d ${projectFolder}/sites/*|rev|cut -d/ -f1|rev); do 
        if [ ${i} == 'xdebug.log' ]; then
            continue
        fi
        if [ ${web_port} == 80 ]; then
        echo -n http://;echo ${i}.dev|cut -d/ -f 2; 
        else
        echo -n http://;echo ${i}.dev:${web_port}|cut -d/ -f 2; 
        fi
done
    else
        echo "*.dev, port:" ${web_port}
        ls -l sites/|cut -d ' ' -f 9
   fi 
fi

if [ ${projectNum} -eq 0 ]; then
    echo "No Projects are found, you can create one by following command."
    echo "For example as below:"
    echo "./create [project name]"
fi
#echo " http://0.0.0.0:${web_port}"

